export default 
  [
    { 
      name: 'BKS Iyengar Yogashala KL', 
      teacher: 'Nandakumar',
      address: '41-1 Jln 1/ 109E, Desa Business Park, Old Klang Road',
      zip: '58100',     
      city: 'Taman Desa',
      state: 'Kuala Lumpur',
      email: 'bksiyogashala@gmail.com',
      contact: '012 320 4115',
      visible: true
    },
    { 
      name: 'Purity Wellness Club', 
      address: 'C-3-5 Seri Gembira Avenue, Taman Gembira',
      teacher: 'Alan Chin',
      zip: '58200',      
      city: 'Taman Desa',
      state: 'Kuala Lumpur',
      email: 'puritywellnessclub@gmail.com',
      contact: '012 701 7984', 
      visible: true
    },
    { 
      name: 'Shradha Yoga', 
      address: 'Desa Sri Hartamas',
      teacher: 'Paarul Metha',
      zip: '50480',      
      city: 'Desa Sri Hartamas',
      state: 'Kuala Lumpur',
      email: 'yogawithparul@hotmail.com',
      contact: '012 307 6577',
      visible: true  
    },
    { 
      name: 'Asana Iyengar Yoga', 
      address: '167 Jalan Limau Purut, Bangsar Park',
      teacher: 'Kalaivani Jeyapalan',
      zip: '59000',      
      city: 'Kuala lumpur',
      state: 'Kuala Lumpur',
      email: 'yogawithvani@hotmail.com',
      contact: '012 372 5155',
      visible: true  
    },
    { 
      name: 'Yogi Step', 
      address: '24-1, Villa Saujanis, Jln 3/38a, Tmn Sri Sinar',
      teacher: 'Yap Sze Yeng',
      zip: '51200',      
      city: 'Segambut',
      state: 'Kuala Lumpur',
      email: 'yogistep80@gmail.com',
      contact: '012 688 5925',
      visible: true  
    },    
    { 
      name: 'TREYOGA', 
      teacher: 'Carol Ong',
      address: 'D3A-9-G Dana 1 Commercial Centre, Jalan PJU1A/46',
      zip: '47301',      
      city: 'Petaling Jaya',
      state: 'Selangor',
      email: 'treyoga@gmail.com',
      contact: '016 339 9888',
      visible: true  
    },    
    { 
      name: 'Shanthi Yoga Centre', 
      teacher: 'Carol Lee',
      address: '19-2, Jalan Equine 1A, Taman Equine',
      zip: '43300',      
      city: 'Seri Kembangan',
      state: 'Selangor',
      email: 'shanthiyogacentre@gmail.com',
      contact: '012 372 5177',
      visible: true  
    },
    { 
      name: 'Iyengar Yoga Studio Setia Alam', 
      teacher: 'Chong Swee, Honan Sia',
      address: '2, AV U13/AV, 1, Jalan Setia Utama AR U13/AR',
      zip: '40170',      
      city: 'Setia Alam',
      state: 'Selangor',
      email: 'siacs31@yahoo.com',
      contact: '013 287 0119',
      visible: true  
    },
    { 
      name: 'Home Studio', 
      teacher: 'Ean See Ng',
      address: '3, Jln USJ 9/3D, UEP Subang Jaya',
      zip: '47620',      
      city: 'Subang Jaya',
      state: 'Selangor',
      email: 'ngeansee@yahoo.com',
      contact: '012 231 1482',
      visible: true  
    },
    { 
      name: 'Tapas Iyengar Yoga Studio', 
      teacher: 'Yoke Ngoh Soon (Mei Soong)',
      address: '2-33, Jalan Puteri 4/6, Bandar Puteri Puchong',
      zip: '47100',      
      city: 'Puchong',
      state: 'Selangor',
      email: 'tapasiyengarstudio@gmail.com',
      contact: '010 453 0282',
      visible: true  
    },
    { 
      name: 'Life Ca-Dio Yoga Studio', 
      teacher: 'Siok Han Liew',
      address: '67-1,Jalan puteri 2/3, Bandar Puteri',
      zip: '47100',      
      city: 'Puchong',
      state: 'Selangor',
      email: 'lifecadio@gmail.com',
      contact: '012 387 7593',
      visible: true 
    },
    { 
      name: 'Iyengar Yoga Bandar Sg Long', 
      teacher: 'Wai Queen, Maya Wong',
      address: '22-2, Jalan SL 1/12, Bandar Sungai Long',
      zip: '43000',      
      city: 'Kajang',
      state: 'Selangor',
      email: 'mayawwq@gmail.com',
      contact: '019 388 9319',
      visible: true  
    },
    { 
      name: 'Iyengar Yoga Sungai Buloh', 
      teacher: 'Suh Min, Angel Yew',
      address: '46, Jalan BRP 2/2, Bukit Rahman Putra',
      zip: '47000',      
      city: 'Sungai Buloh',
      state: 'Selangor',
      email: 'angelyewsm@gmail.com',
      contact: '012 223 6788',
      visible: true  
    },
    { 
      name: 'Breazy Yoga', 
      teacher: 'Kazumi Fujimura',
      address: '29A, Jalan Seri Baiduri1, Taman Seri Baiduri, Bandar Teknologi',
      website: 'https://www.breazyyoga.com/',
      zip: '43500',      
      city: 'Kajang',
      state: 'Selangor',
      email: 'breazyyoga@yahoo.com',
      contact: '012 231 1482',
      visible: true  
    },
    { 
      name: 'Pure Mind Yoga Studio', 
      teacher: 'Mei Yan Wong',
      address: 'A-1-3, Block A, Pusat Komersial Parklane,7/26, Kelana Jaya',
      zip: '47301',      
      city: 'Kelana Jaya',
      state: 'Selangor',
      email: 'mywong83@hotmail.com',
      contact: '012 278 3752',
      visible: true  
    },
    { 
      name: 'Iyengar Yoga Studio Klang', 
      teacher: 'Seong Ngoh, Emily Ang',
      address: 'B4-12-2, Jalan Batu Nilam 3, Bandar Bukit Tinggi',
      zip: '41200',      
      city: 'Klang',
      state: 'Selangor',
      email: 'email2asn@gmail.com',
      contact: '017 265 7943',
      visible: true  
    },
    { 
      name: 'Yoga House', 
      teacher: 'Sumitra Sekaran',
      address: '11, Jalan 16/5, Section 16',
      zip: '46350',      
      city: 'Petaling Jaya',
      state: 'Selangor',
      email: 'sumitra@yogahouse.com.my',
      website: 'www.yogahouse.com.my',
      contact: '017 265 7943',
      visible: true  
    },
    { 
      name: 'Independent Yoga Teacher', 
      teacher: 'Carol Lee',
      address: '',
      zip: '43200',      
      city: 'Kajang',
      state: 'Selangor',
      email: 'leecarol0708@gmail.com',
      contact: '012 372 5177',
      visible: true  
    },
    { 
      name: 'Independent Yoga Teacher', 
      teacher: 'Lena Wong',
      address: '',
      zip: '42600',      
      city: 'Jenjarom',
      state: 'Selangor',
      email: 'lena_er222@hotmail.com',
      contact: '012 931 6633',
      visible: true  
    },
    { 
      name: 'Independent Yoga Teacher', 
      teacher: 'Melissa Chan',
      address: '',
      zip: '47100',      
      city: 'Puchong',
      state: 'Selangor',
      email: 'melisachan21@gmail.com',
      contact: '016 273 6726',
      visible: true  
    },
    { 
      name: 'Independent Yoga Teacher', 
      teacher: 'Michael Peter s/o Andrew',
      address: '',
      zip: '43200',      
      city: 'Cheras',
      state: 'Selangor',
      email: 'michael_peter5@hotmail.com',
      contact: '012 386 7766',
      visible: true  
    },
    { 
      name: 'Independent Yoga Teacher', 
      teacher: 'Natasya Chng',
      address: '',
      zip: '47600',      
      city: 'Subang jaya',
      state: 'Selangor',
      email: 'natasyachng@gmail.com',
      contact: '016 477 6867',
      visible: true  
    },
    { 
      name: 'Independent Yoga Teacher', 
      teacher: 'Phaik Yoong, Christina Wong',
      address: '',
      zip: '47110',      
      city: 'Puchong',
      state: 'Selangor',
      email: 'cpywongster@gmail.com',
      contact: '019 388 0712',
      visible: true  
    },
    { 
      name: 'Independent Yoga Teacher', 
      teacher: 'Premalatha Govindasamy',
      address: '',
      zip: '46400',      
      city: 'Petaling Jaya',
      state: 'Selangor',
      email: 'avimy@yahoo.com',
      contact: '017 612 5501',
      visible: true  
    },
    { 
      name: 'Independent Yoga Teacher', 
      teacher: 'Tara Wong Sie Yeun Kok',
      address: '',
      zip: '43000',      
      city: 'Taman Bukit Mewah',
      state: 'Selangor',
      email: 'wongsieyeun@gmail.com',
      contact: '012 971 7105',
      visible: true  
    },
    { 
      name: 'Independent Yoga Teacher', 
      teacher: 'Veun Chin',
      address: '',
      zip: '47100',      
      city: 'Puchong',
      state: 'Selangor',
      email: 'veun@yahoo.com',
      contact: '',
      visible: true  
    },
    { 
      name: 'Independent Yoga Teacher', 
      teacher: 'Yook Chin Yap',
      address: '',
      zip: '47610',      
      city: 'Subang Jaya',
      state: 'Selangor',
      email: 'yookchin61@gmail.com',
      contact: '017 235 7733',
      visible: true  
    },
    { 
      name: 'Iyengar Yoga Kampar', 
      teacher: 'Suh Fong, Joanne Yew',
      address: '52A Jalan Kolej, Taman Kolej Perdana',
      zip: '31900',      
      city: 'Kampar',
      state: 'Perak',
      email: 'joanneyewsf@gmail.com',
      contact: '016 441 2448',
      visible: true  
    },
    { 
      name: 'Iyengar Yoga Studio Langkap', 
      teacher: 'Wai Yoke, Patern Toh',
      address: '15, Jalan Besar ',
      zip: '36700',      
      city: 'Langkap',
      state: 'Perak',
      email: 'waiyoke82@yahoo.com',
      contact: '016 523 3602',
      visible: true  
    },
    { 
      name: 'Independent Yoga Teacher', 
      teacher: 'Narenthran S.Virakannu',
      address: '',
      zip: '14000',      
      city: 'Bukit Mertajam',
      state: 'Pulau Pinang',
      email: 'naren69@gmail.com',
      contact: '012 421 6045',
      visible: true  
    },
    { 
      name: 'The Seeds Iyengar Yoga Studio', 
      teacher: 'Sin Yue Tan',
      address: '01-31, Jalan Austin Perdana 2/25, Taman Austin Perdana, 81100 Johor Bahru, Malaysia',
      zip: '81100',      
      city: 'Johor Bahru',
      state: 'Johor',
      email: 'iyengaryogajb@gmail.com',
      contact: '019 885 3857',
      visible: true  
    },
    { 
      name: 'Independent Yoga Teacher', 
      teacher: 'Cheng Yee, Joreen Wong',
      address: '',
      zip: '81100',      
      city: 'Taman Daya',
      state: 'Johor',
      email: 'chengyee1983@hotmail.com',
      contact: '019 713 6909',
      visible: true  
    },
    { 
      name: 'Independent Yoga Teacher', 
      teacher: 'Michaela Hasenauer',
      address: '',
      zip: '07000',      
      city: 'Langkawi',
      state: 'Kedah',
      email: 'michash19@gmail.com',
      contact: '019 367 7024',
      visible: true  
    },
    { 
      name: 'Yoga Home', 
      teacher: 'Soh Kheng, Tracy Yu',
      address: 'No.696, Lorong 26, Tabuan Tranquality',
      zip: '93350',      
      city: 'Kuching',
      state: 'Sarawak',
      email: 'tracyu33@gmail.com',
      contact: '019 267 1431',
      visible: true  
    },
    { 
      name: 'Mahat Yoga', 
      teacher: 'Kian Voon, Valerie Chai',
      address: '1st Floor, 605, Lot 1516, Jalan Penrissen, Kota Sentosa',
      zip: '93250',      
      city: 'Kuching',
      state: 'Sarawak',
      email: '1108ckv@gmail.com',
      contact: '012 895 8998',
      visible: true  
    },
  ]
